### ISSUE TITLE
JSON5 & 6

### ISSUE THREAD

**Issue by tonycwhite** [Dullage/ESP-MQTT-LEDStrip#6]
i get an error when building
`DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6`

ive tried a very basic attempt to change the word buffer to document, but it throws up further errors. As im not a coding expert, im not sure what else to do with the code.

**Comment by dullage** [comment]
Ideally I’d refactor this repo to work with the latest version of that library but for now I’d recommend simply using a 5x version.

Assuming your using the Arduino IDE, when you install the library you should get a drop down allowing you to pick a 5x version (the latest 5x version works for me). 

Hope this helps.

**Comment by tonycwhite** [comment]
ahh, yes, makes sense to roll back the arduinoJson library. VMT! Looking forward to getting this up and running.
