### ISSUE TITLE
RGB Colours are not retained while toggling using Home Assistant

### ISSUE THREAD

**Issue by bmangodt** [Dullage/ESP-MQTT-LEDStrip#7]
If I toggle the light off and on again using Home Assistant and using the simple light config provided, the state defaults to a RGB value of [255,147,41]. Is this normal behaviour for it to not save the last used RGB values?

**Comment by dullage** [comment]
It’s is indeed. Using the example sends the command of “1” when the light is turned on, the code uses the default colours for the All On mode which is the RGB value you see (a warm light). 

I had a quick look at potentially changing the payload_on value but I think this will break the state change detection. 

If you’re after different behaviour a couple of options come to mind:

1. Change the hard coded default light colour in the code (lines 130 to 132).
2. Add automations to HA to set the colour you want when the light turns on. 

I’ve also seen that you can create temporary scenes on the fly now which may be of use here if your looking to restore the last state. I haven’t played with this feature myself but worth a look. 

Hope this helps.

**Comment by bmangodt** [comment]
Thanks for the quick response! I might have a look at the code when I find the time, in the meantime I will use your suggestion of using an automation. Thanks for the tips!
